-- Blog artwork generated by the `blog-image` edge function (Gemini).
-- Run once in the Supabase SQL editor.

create table if not exists public.blog_images (
  slug text primary key,
  hero_url text not null,
  card_url text not null,
  og_url text not null,
  prompt text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select on public.blog_images to anon;
grant select on public.blog_images to authenticated;
grant all on public.blog_images to service_role;

alter table public.blog_images enable row level security;

drop policy if exists "Blog images are public" on public.blog_images;
create policy "Blog images are public"
  on public.blog_images for select
  to anon, authenticated
  using (true);

-- Public storage bucket for the artwork.
insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Blog images readable" on storage.objects;
create policy "Blog images readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'blog-images');
