import { forwardRef, type HTMLAttributes, type Ref } from "react";
import type { LucideIcon, LucideProps } from "lucide-react";

export type { LucideIcon, LucideProps } from "lucide-react";

const emojiFor = (name: string): string => {
  if (name === "EyeOff") return "🙈";
  if (name === "VolumeX") return "🔇";
  if (name === "Unplug") return "🔌";
  if (name === "StarOff") return "✩";
  if (name === "PinOff") return "📍";
  if (name === "ArrowUpDown") return "↕";
  if (name === "Undo2") return "↶";
  if (name === "Redo2") return "↷";
  if (name.includes("ArrowLeft") || name === "ChevronLeft") return "←";
  if (name.includes("ArrowRight") || name === "ChevronRight") return "→";
  if (name === "ArrowUp" || name === "ChevronUp") return "↑";
  if (name === "ArrowDown" || name === "ChevronDown") return "↓";
  if (name.startsWith("Alert")) return "⚠️";
  if (name.startsWith("Check")) return "✅";
  if (name === "X") return "❌";
  if (name.includes("Loader") || name.includes("Clock") || name.includes("History")) return "⏳";
  if (name.includes("Search")) return "🔎";
  if (name.includes("Download") || name === "FileDown") return "↓";
  if (name.includes("Upload")) return "↑";
  if (name.includes("Copy") || name.includes("Clipboard")) return "📋";
  if (name.includes("Save")) return "💾";
  if (name.includes("Trash")) return "🗑️";
  if (name.includes("Share") || name.includes("Send")) return "📤";
  if (name.includes("Plus")) return "➕";
  if (name.includes("Minus")) return "➖";
  if (name.includes("Refresh") || name.includes("Rotate") || name.includes("Shuffle")) return "🔄";
  if (name.includes("ExternalLink")) return "↗";
  if (name.includes("Link")) return "🔗";
  if (name.includes("Eye")) return "👁️";
  if (name.includes("Maximize")) return "🔲";
  if (name.includes("Minimize")) return "🔳";
  if (name.includes("Play")) return "▶️";
  if (name.includes("Pause")) return "⏸️";
  if (name.includes("Volume")) return "🔊";
  if (name.includes("Lock")) return "🔒";
  if (name.includes("Key") || name.includes("Unlock")) return "🔑";
  if (name.includes("LogOut")) return "🚪";
  if (name.includes("LogIn")) return "🔓";
  if (name.includes("User")) return name.includes("Users") ? "👥" : "👤";
  if (name.includes("Mail")) return "✉️";
  if (name.includes("Message") || name.includes("Chat")) return "💬";
  if (name.includes("Bell")) return "🔔";
  if (name.includes("Bookmark") || name.includes("BookMarked")) return "🔖";
  if (name === "Pin") return "📌";
  if (name.includes("Book")) return "📖";
  if (name.includes("Folder")) return "📁";
  if (name.includes("File")) return "📄";
  if (name.includes("Image") || name.includes("Camera")) return "🖼️";
  if (name.includes("GitBranch")) return "🌿";
  if (name.includes("Lightbulb")) return "💡";
  if (name.includes("Palette") || name.includes("Paintbrush")) return "🎨";
  if (name.includes("Pen") || name.includes("Pencil") || name.includes("Edit")) return "✏️";
  if (name.includes("Circle")) return "🔘";
  if (name.includes("Square")) return "🔳";
  if (name.includes("Triangle")) return "🔺";
  if (name.includes("Shape")) return "🔷";
  if (name.includes("Grid") || name.includes("Layout") || name.includes("Layers") || name.includes("Panel")) return "🗂️";
  if (name.includes("List") || name.includes("Table")) return "📋";
  if (name.includes("Wand") || name.includes("Sparkle")) return "✨";
  if (name.includes("Rocket")) return "🚀";
  if (name.includes("Flame")) return "🔥";
  if (name.includes("Heart")) return "❤️";
  if (name.includes("Star")) return "⭐";
  if (name.includes("Crown")) return "👑";
  if (name.includes("Shield")) return "🛡️";
  if (name.includes("Settings")) return "⚙️";
  if (name.includes("Info")) return "ℹ️";
  if (name.includes("Help")) return "❓";
  if (name.includes("CreditCard")) return "💳";
  if (name.includes("Wallet") || name.includes("Coins")) return "🪙";
  if (name.includes("Shopping")) return "🛍️";
  if (name.includes("Trending") || name.includes("LineChart")) return "📈";
  if (name.includes("Chart")) return "📊";
  if (name.includes("Globe")) return "🌐";
  if (name.includes("Compass")) return "🧭";
  if (name.includes("Database")) return "🗄️";
  if (name.includes("Cloud")) return "☁️";
  if (name.includes("Building")) return "🏢";
  if (name.includes("Megaphone")) return "📣";
  if (name.includes("Newspaper")) return "📰";
  if (name.includes("Smartphone")) return "📱";
  if (name.includes("Mic")) return "🎙️";
  if (name.includes("Keyboard")) return "⌨️";
  if (name.includes("Printer")) return "🖨️";
  if (name.includes("Puzzle")) return "🧩";
  if (name.includes("Wrench")) return "🔧";
  if (name.includes("Target")) return "🎯";
  if (name.includes("Zap")) return "⚡";
  if (name.includes("Smile")) return "🙂";
  if (name.includes("Facebook")) return "📘";
  if (name.includes("Instagram")) return "📸";
  if (name.includes("Linkedin")) return "💼";
  if (name.includes("Twitter")) return "🐦";
  if (name.includes("Type")) return "🔤";
  if (name.includes("Sticker") || name.includes("StickyNote")) return "🏷️";
  if (name.includes("Paperclip")) return "📎";
  if (name.includes("Scissors")) return "✂️";
  if (name.includes("Plug")) return "🔌";
  if (name.includes("Radio")) return "📻";
  if (name.includes("More") || name.includes("Grip") || name === "Dot") return "🔹";
  if (name.includes("Hash")) return "🔢";
  if (name.includes("Box")) return "📦";
  return "🔹";
};

const icon = (name: string): LucideIcon =>
  forwardRef<SVGSVGElement, LucideProps>(function EmojiIcon(
    { className, style, size, color, ...props },
    ref,
  ) {
    const { strokeWidth: _strokeWidth, absoluteStrokeWidth: _absoluteStrokeWidth, ...rest } = props;
    return (
      <span
        {...(rest as HTMLAttributes<HTMLSpanElement>)}
        ref={ref as unknown as Ref<HTMLSpanElement>}
        aria-hidden={rest["aria-label"] ? undefined : true}
        className={`inline-flex shrink-0 items-center justify-center not-italic leading-none ${className || ""}`}
        style={{ fontSize: typeof size === "number" ? size : undefined, color, ...style }}
      >
        {emojiFor(name)}
      </span>
    );
  }) as LucideIcon;

export const AlertCircle = icon("AlertCircle");
export const AlertTriangle = icon("AlertTriangle");
export const ArrowDown = icon("ArrowDown");
export const ArrowLeft = icon("ArrowLeft");
export const ArrowRight = icon("ArrowRight");
export const ArrowUp = icon("ArrowUp");
export const ArrowUpDown = icon("ArrowUpDown");
export const BarChart3 = icon("BarChart3");
export const Bell = icon("Bell");
export const BookMarked = icon("BookMarked");
export const BookOpen = icon("BookOpen");
export const Bookmark = icon("Bookmark");
export const Box = icon("Box");
export const Building2 = icon("Building2");
export const Camera = icon("Camera");
export const Check = icon("Check");
export const CheckCheck = icon("CheckCheck");
export const CheckCircle2 = icon("CheckCircle2");
export const CheckSquare = icon("CheckSquare");
export const ChevronDown = icon("ChevronDown");
export const ChevronLeft = icon("ChevronLeft");
export const ChevronRight = icon("ChevronRight");
export const ChevronUp = icon("ChevronUp");
export const Circle = icon("Circle");
export const ClipboardPaste = icon("ClipboardPaste");
export const Clock = icon("Clock");
export const Cloud = icon("Cloud");
export const Coins = icon("Coins");
export const Compass = icon("Compass");
export const Copy = icon("Copy");
export const CreditCard = icon("CreditCard");
export const Crown = icon("Crown");
export const Database = icon("Database");
export const Dot = icon("Dot");
export const Download = icon("Download");
export const Edit3 = icon("Edit3");
export const ExternalLink = icon("ExternalLink");
export const Eye = icon("Eye");
export const EyeOff = icon("EyeOff");
export const Facebook = icon("Facebook");
export const FileCode = icon("FileCode");
export const FileDown = icon("FileDown");
export const FileImage = icon("FileImage");
export const FilePlus = icon("FilePlus");
export const FileText = icon("FileText");
export const Files = icon("Files");
export const Flame = icon("Flame");
export const Folder = icon("Folder");
export const FolderOpen = icon("FolderOpen");
export const FolderPlus = icon("FolderPlus");
export const Folders = icon("Folders");
export const GitBranch = icon("GitBranch");
export const Globe = icon("Globe");
export const Grid2X2 = icon("Grid2X2");
export const Grid3X3 = icon("Grid3X3");
export const Grid3x3 = icon("Grid3x3");
export const GripVertical = icon("GripVertical");
export const Hash = icon("Hash");
export const Heart = icon("Heart");
export const HelpCircle = icon("HelpCircle");
export const History = icon("History");
export const Image = icon("Image");
export const ImageIcon = icon("ImageIcon");
export const Info = icon("Info");
export const Instagram = icon("Instagram");
export const KeyRound = icon("KeyRound");
export const Keyboard = icon("Keyboard");
export const Layers = icon("Layers");
export const Layers3 = icon("Layers3");
export const LayoutGrid = icon("LayoutGrid");
export const LayoutTemplate = icon("LayoutTemplate");
export const Lightbulb = icon("Lightbulb");
export const LineChart = icon("LineChart");
export const Link = icon("Link");
export const Link2 = icon("Link2");
export const Linkedin = icon("Linkedin");
export const List = icon("List");
export const ListChecks = icon("ListChecks");
export const Loader2 = icon("Loader2");
export const Lock = icon("Lock");
export const LogIn = icon("LogIn");
export const LogOut = icon("LogOut");
export const Mail = icon("Mail");
export const Maximize2 = icon("Maximize2");
export const Megaphone = icon("Megaphone");
export const MessageCircle = icon("MessageCircle");
export const MessageSquare = icon("MessageSquare");
export const MessageSquarePlus = icon("MessageSquarePlus");
export const Mic = icon("Mic");
export const Minimize2 = icon("Minimize2");
export const Minus = icon("Minus");
export const MoreHorizontal = icon("MoreHorizontal");
export const Newspaper = icon("Newspaper");
export const Paintbrush = icon("Paintbrush");
export const Palette = icon("Palette");
export const PanelLeft = icon("PanelLeft");
export const PanelLeftClose = icon("PanelLeftClose");
export const PanelLeftOpen = icon("PanelLeftOpen");
export const Paperclip = icon("Paperclip");
export const Pause = icon("Pause");
export const PenLine = icon("PenLine");
export const PenTool = icon("PenTool");
export const Pencil = icon("Pencil");
export const Pin = icon("Pin");
export const PinOff = icon("PinOff");
export const Play = icon("Play");
export const Plug = icon("Plug");
export const Plus = icon("Plus");
export const Printer = icon("Printer");
export const Puzzle = icon("Puzzle");
export const Radio = icon("Radio");
export const Redo2 = icon("Redo2");
export const RefreshCw = icon("RefreshCw");
export const Rocket = icon("Rocket");
export const RotateCcw = icon("RotateCcw");
export const Save = icon("Save");
export const Scissors = icon("Scissors");
export const Search = icon("Search");
export const Send = icon("Send");
export const Settings = icon("Settings");
export const Settings2 = icon("Settings2");
export const Shapes = icon("Shapes");
export const Share2 = icon("Share2");
export const ShieldCheck = icon("ShieldCheck");
export const ShoppingBag = icon("ShoppingBag");
export const Shuffle = icon("Shuffle");
export const Smartphone = icon("Smartphone");
export const Smile = icon("Smile");
export const Sparkle = icon("Sparkle");
export const Sparkles = icon("Sparkles");
export const Square = icon("Square");
export const Star = icon("Star");
export const StarOff = icon("StarOff");
export const Sticker = icon("Sticker");
export const StickyNote = icon("StickyNote");
export const Table = icon("Table");
export const Target = icon("Target");
export const Trash2 = icon("Trash2");
export const TrendingUp = icon("TrendingUp");
export const Triangle = icon("Triangle");
export const Twitter = icon("Twitter");
export const Type = icon("Type");
export const Undo2 = icon("Undo2");
export const Unlock = icon("Unlock");
export const Unplug = icon("Unplug");
export const Upload = icon("Upload");
export const UserPlus = icon("UserPlus");
export const Users = icon("Users");
export const Volume2 = icon("Volume2");
export const VolumeX = icon("VolumeX");
export const Wallet = icon("Wallet");
export const Wand = icon("Wand");
export const Wand2 = icon("Wand2");
export const Wrench = icon("Wrench");
export const X = icon("X");
export const Zap = icon("Zap");
