/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiInfoRouteImport } from './routes/ai-info'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as ClaimInvitationRouteImport } from './routes/claim-invitation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StartRouteImport } from './routes/start'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEditorRouteImport } from './routes/_app/editor'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppGenerateRouteImport } from './routes/_app/generate'
import { Route as AppIconsRouteImport } from './routes/_app/icons'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppLogosRouteImport } from './routes/_app/logos'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPresentRouteImport } from './routes/_app/present'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSavedAppsRouteImport } from './routes/_app/saved-apps'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppWizardRouteImport } from './routes/_app/wizard'
import { Route as AppYourAppsRouteImport } from './routes/_app/your-apps'
import { Route as AppsIdRouteImport } from './routes/apps.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BrandTemplatesIndexRouteImport } from './routes/brand-templates.index'
import { Route as BrandTemplatesIdRouteImport } from './routes/brand-templates.$id'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as ConnectAuthorizeRouteImport } from './routes/connect.authorize'
import { Route as CreateBrandingRouteImport } from './routes/create_.branding'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OutreachUnsubscribeRouteImport } from './routes/outreach.unsubscribe'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as AppAdminSectionRouteImport } from './routes/_app/admin.$section'
import { Route as AppAppsAddRouteImport } from './routes/_app/apps.add'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets.index'
import { Route as AppAssetsIdRouteImport } from './routes/_app/assets.$id'
import { Route as AppBrandIndexRouteImport } from './routes/_app/brand.index'
import { Route as AppBrandIdRouteImport } from './routes/_app/brand.$id'
import { Route as AppBrandsIndexRouteImport } from './routes/_app/brands.index'
import { Route as AppBrandsIdRouteImport } from './routes/_app/brands.$id'
import { Route as AppCreateIndexRouteImport } from './routes/_app/create.index'
import { Route as AppCreateChatRouteImport } from './routes/_app/create.chat'
import { Route as AppCreateGenerateRouteImport } from './routes/_app/create.generate'
import { Route as AppDesignsIndexRouteImport } from './routes/_app/designs.index'
import { Route as AppDesignsIdRouteImport } from './routes/_app/designs.$id'
import { Route as AppDeveloperActivateRouteImport } from './routes/_app/developer.activate'
import { Route as AppMyAppsIndexRouteImport } from './routes/_app/my-apps.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects.new'
import { Route as AppRocketIdRouteImport } from './routes/_app/rocket.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings.account'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings.billing'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings.integrations'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings.notifications'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings.profile'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings.team'
import { Route as AppStudioIndexRouteImport } from './routes/_app/studio.index'
import { Route as AppStudioIdRouteImport } from './routes/_app/studio.$id'
import { Route as BlogAuthorIdRouteImport } from './routes/blog.author.$id'
import { Route as ShareAssetTokenRouteImport } from './routes/share.asset.$token'
import { Route as ShareProjectTokenRouteImport } from './routes/share.project.$token'
import { Route as AppBrandsIdIndexRouteImport } from './routes/_app/brands.$id.index'
import { Route as AppBrandsIdBrandBookRouteImport } from './routes/_app/brands.$id.brand-book'
import { Route as AppBrandsIdFontsRouteImport } from './routes/_app/brands.$id.fonts'
import { Route as AppBrandsIdPaletteRouteImport } from './routes/_app/brands.$id.palette'
import { Route as AppBrandsIdSocialIconsRouteImport } from './routes/_app/brands.$id.social-icons'
import { Route as AppDeveloperAppsClientIdRouteImport } from './routes/_app/developer.apps.$clientId'
import { Route as AppMyAppsIdAnalyticsRouteImport } from './routes/_app/my-apps.$id.analytics'
import { Route as AppMyAppsIdEditRouteImport } from './routes/_app/my-apps.$id.edit'
import { Route as AppMyAppsIdRevenueRouteImport } from './routes/_app/my-apps.$id.revenue'
import { Route as AppProjectsIdBrandKitRouteImport } from './routes/_app/projects.$id_.brand-kit'
import { Route as AppProjectsIdFontsRouteImport } from './routes/_app/projects.$id_.fonts'
import { Route as AppProjectsIdGuidelinesRouteImport } from './routes/_app/projects.$id_.guidelines'
import { Route as AppProjectsIdHubRouteImport } from './routes/_app/projects.$id_.hub'
import { Route as AppProjectsIdLogoFilesRouteImport } from './routes/_app/projects.$id_.logo-files'
import { Route as AppProjectsIdPalettesRouteImport } from './routes/_app/projects.$id_.palettes'
import { Route as AppProjectsIdSocialRouteImport } from './routes/_app/projects.$id_.social'
import { Route as AppProjectsIdWebsitesRouteImport } from './routes/_app/projects.$id_.websites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfoRoute = AiInfoRouteImport.update({
  id: '/ai-info',
  path: '/ai-info',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimInvitationRoute = ClaimInvitationRouteImport.update({
  id: '/claim-invitation',
  path: '/claim-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppIconsRoute = AppIconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppLogosRoute = AppLogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPresentRoute = AppPresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedAppsRoute = AppSavedAppsRouteImport.update({
  id: '/saved-apps',
  path: '/saved-apps',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardRoute = AppWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppYourAppsRoute = AppYourAppsRouteImport.update({
  id: '/your-apps',
  path: '/your-apps',
  getParentRoute: () => AppRoute,
} as any)
const AppsIdRoute = AppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandTemplatesIndexRoute = BrandTemplatesIndexRouteImport.update({
  id: '/brand-templates/',
  path: '/brand-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandTemplatesIdRoute = BrandTemplatesIdRouteImport.update({
  id: '/brand-templates/$id',
  path: '/brand-templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectAuthorizeRoute = ConnectAuthorizeRouteImport.update({
  id: '/connect/authorize',
  path: '/connect/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBrandingRoute = CreateBrandingRouteImport.update({
  id: '/create_/branding',
  path: '/create/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachUnsubscribeRoute = OutreachUnsubscribeRouteImport.update({
  id: '/outreach/unsubscribe',
  path: '/outreach/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSectionRoute = AppAdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAppsAddRoute = AppAppsAddRouteImport.update({
  id: '/apps/add',
  path: '/apps/add',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIdRoute = AppAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandIndexRoute = AppBrandIndexRouteImport.update({
  id: '/brand/',
  path: '/brand/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandIdRoute = AppBrandIdRouteImport.update({
  id: '/brand/$id',
  path: '/brand/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIndexRoute = AppBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIdRoute = AppBrandsIdRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateIndexRoute = AppCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateChatRoute = AppCreateChatRouteImport.update({
  id: '/create/chat',
  path: '/create/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateGenerateRoute = AppCreateGenerateRouteImport.update({
  id: '/create/generate',
  path: '/create/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignsIndexRoute = AppDesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignsIdRoute = AppDesignsIdRouteImport.update({
  id: '/designs/$id',
  path: '/designs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperActivateRoute = AppDeveloperActivateRouteImport.update({
  id: '/developer/activate',
  path: '/developer/activate',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAppsIndexRoute = AppMyAppsIndexRouteImport.update({
  id: '/my-apps/',
  path: '/my-apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRocketIdRoute = AppRocketIdRouteImport.update({
  id: '/rocket/$id',
  path: '/rocket/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppStudioIndexRoute = AppStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioIdRoute = AppStudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => AppRoute,
} as any)
const BlogAuthorIdRoute = BlogAuthorIdRouteImport.update({
  id: '/blog/author/$id',
  path: '/blog/author/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareAssetTokenRoute = ShareAssetTokenRouteImport.update({
  id: '/share/asset/$token',
  path: '/share/asset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareProjectTokenRoute = ShareProjectTokenRouteImport.update({
  id: '/share/project/$token',
  path: '/share/project/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrandsIdIndexRoute = AppBrandsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBrandsIdRoute,
} as any)
const AppBrandsIdBrandBookRoute = AppBrandsIdBrandBookRouteImport.update({
  id: '/brand-book',
  path: '/brand-book',
  getParentRoute: () => AppBrandsIdRoute,
} as any)
const AppBrandsIdFontsRoute = AppBrandsIdFontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => AppBrandsIdRoute,
} as any)
const AppBrandsIdPaletteRoute = AppBrandsIdPaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => AppBrandsIdRoute,
} as any)
const AppBrandsIdSocialIconsRoute = AppBrandsIdSocialIconsRouteImport.update({
  id: '/social-icons',
  path: '/social-icons',
  getParentRoute: () => AppBrandsIdRoute,
} as any)
const AppDeveloperAppsClientIdRoute =
  AppDeveloperAppsClientIdRouteImport.update({
    id: '/developer/apps/$clientId',
    path: '/developer/apps/$clientId',
    getParentRoute: () => AppRoute,
  } as any)
const AppMyAppsIdAnalyticsRoute = AppMyAppsIdAnalyticsRouteImport.update({
  id: '/my-apps/$id/analytics',
  path: '/my-apps/$id/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAppsIdEditRoute = AppMyAppsIdEditRouteImport.update({
  id: '/my-apps/$id/edit',
  path: '/my-apps/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAppsIdRevenueRoute = AppMyAppsIdRevenueRouteImport.update({
  id: '/my-apps/$id/revenue',
  path: '/my-apps/$id/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdBrandKitRoute = AppProjectsIdBrandKitRouteImport.update({
  id: '/projects/$id_/brand-kit',
  path: '/projects/$id/brand-kit',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdFontsRoute = AppProjectsIdFontsRouteImport.update({
  id: '/projects/$id_/fonts',
  path: '/projects/$id/fonts',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdGuidelinesRoute = AppProjectsIdGuidelinesRouteImport.update({
  id: '/projects/$id_/guidelines',
  path: '/projects/$id/guidelines',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdHubRoute = AppProjectsIdHubRouteImport.update({
  id: '/projects/$id_/hub',
  path: '/projects/$id/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdLogoFilesRoute = AppProjectsIdLogoFilesRouteImport.update({
  id: '/projects/$id_/logo-files',
  path: '/projects/$id/logo-files',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdPalettesRoute = AppProjectsIdPalettesRouteImport.update({
  id: '/projects/$id_/palettes',
  path: '/projects/$id/palettes',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdSocialRoute = AppProjectsIdSocialRouteImport.update({
  id: '/projects/$id_/social',
  path: '/projects/$id/social',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdWebsitesRoute = AppProjectsIdWebsitesRouteImport.update({
  id: '/projects/$id_/websites',
  path: '/projects/$id/websites',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-info': typeof AiInfoRoute
  '/brand-kit': typeof BrandKitRoute
  '/claim-invitation': typeof ClaimInvitationRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/editor': typeof AppEditorRoute
  '/files': typeof AppFilesRoute
  '/generate': typeof AppGenerateRoute
  '/icons': typeof AppIconsRoute
  '/insights': typeof AppInsightsRoute
  '/library': typeof AppLibraryRoute
  '/logos': typeof AppLogosRoute
  '/notifications': typeof AppNotificationsRoute
  '/present': typeof AppPresentRoute
  '/saved': typeof AppSavedRoute
  '/saved-apps': typeof AppSavedAppsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/trash': typeof AppTrashRoute
  '/wizard': typeof AppWizardRoute
  '/your-apps': typeof AppYourAppsRoute
  '/apps/$id': typeof AppsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brand-templates/$id': typeof BrandTemplatesIdRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/connect/authorize': typeof ConnectAuthorizeRoute
  '/create/branding': typeof CreateBrandingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/outreach/unsubscribe': typeof OutreachUnsubscribeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/brand-templates/': typeof BrandTemplatesIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/$section': typeof AppAdminSectionRoute
  '/apps/add': typeof AppAppsAddRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/brand/$id': typeof AppBrandIdRoute
  '/brands/$id': typeof AppBrandsIdRouteWithChildren
  '/create/chat': typeof AppCreateChatRoute
  '/create/generate': typeof AppCreateGenerateRoute
  '/designs/$id': typeof AppDesignsIdRoute
  '/developer/activate': typeof AppDeveloperActivateRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/rocket/$id': typeof AppRocketIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/studio/$id': typeof AppStudioIdRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/share/asset/$token': typeof ShareAssetTokenRoute
  '/share/project/$token': typeof ShareProjectTokenRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/brand/': typeof AppBrandIndexRoute
  '/brands/': typeof AppBrandsIndexRoute
  '/create/': typeof AppCreateIndexRoute
  '/designs/': typeof AppDesignsIndexRoute
  '/my-apps/': typeof AppMyAppsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/studio/': typeof AppStudioIndexRoute
  '/brands/$id/brand-book': typeof AppBrandsIdBrandBookRoute
  '/brands/$id/fonts': typeof AppBrandsIdFontsRoute
  '/brands/$id/palette': typeof AppBrandsIdPaletteRoute
  '/brands/$id/social-icons': typeof AppBrandsIdSocialIconsRoute
  '/developer/apps/$clientId': typeof AppDeveloperAppsClientIdRoute
  '/my-apps/$id/analytics': typeof AppMyAppsIdAnalyticsRoute
  '/my-apps/$id/edit': typeof AppMyAppsIdEditRoute
  '/my-apps/$id/revenue': typeof AppMyAppsIdRevenueRoute
  '/projects/$id/brand-kit': typeof AppProjectsIdBrandKitRoute
  '/projects/$id/fonts': typeof AppProjectsIdFontsRoute
  '/projects/$id/guidelines': typeof AppProjectsIdGuidelinesRoute
  '/projects/$id/hub': typeof AppProjectsIdHubRoute
  '/projects/$id/logo-files': typeof AppProjectsIdLogoFilesRoute
  '/projects/$id/palettes': typeof AppProjectsIdPalettesRoute
  '/projects/$id/social': typeof AppProjectsIdSocialRoute
  '/projects/$id/websites': typeof AppProjectsIdWebsitesRoute
  '/brands/$id/': typeof AppBrandsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-info': typeof AiInfoRoute
  '/brand-kit': typeof BrandKitRoute
  '/claim-invitation': typeof ClaimInvitationRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/editor': typeof AppEditorRoute
  '/files': typeof AppFilesRoute
  '/generate': typeof AppGenerateRoute
  '/icons': typeof AppIconsRoute
  '/insights': typeof AppInsightsRoute
  '/library': typeof AppLibraryRoute
  '/logos': typeof AppLogosRoute
  '/notifications': typeof AppNotificationsRoute
  '/present': typeof AppPresentRoute
  '/saved': typeof AppSavedRoute
  '/saved-apps': typeof AppSavedAppsRoute
  '/templates': typeof AppTemplatesRoute
  '/trash': typeof AppTrashRoute
  '/wizard': typeof AppWizardRoute
  '/your-apps': typeof AppYourAppsRoute
  '/apps/$id': typeof AppsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brand-templates/$id': typeof BrandTemplatesIdRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/connect/authorize': typeof ConnectAuthorizeRoute
  '/create/branding': typeof CreateBrandingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/outreach/unsubscribe': typeof OutreachUnsubscribeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/brand-templates': typeof BrandTemplatesIndexRoute
  '/compare': typeof CompareIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/$section': typeof AppAdminSectionRoute
  '/apps/add': typeof AppAppsAddRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/brand/$id': typeof AppBrandIdRoute
  '/create/chat': typeof AppCreateChatRoute
  '/create/generate': typeof AppCreateGenerateRoute
  '/designs/$id': typeof AppDesignsIdRoute
  '/developer/activate': typeof AppDeveloperActivateRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/rocket/$id': typeof AppRocketIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/studio/$id': typeof AppStudioIdRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/share/asset/$token': typeof ShareAssetTokenRoute
  '/share/project/$token': typeof ShareProjectTokenRoute
  '/assets': typeof AppAssetsIndexRoute
  '/brand': typeof AppBrandIndexRoute
  '/brands': typeof AppBrandsIndexRoute
  '/create': typeof AppCreateIndexRoute
  '/designs': typeof AppDesignsIndexRoute
  '/my-apps': typeof AppMyAppsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/studio': typeof AppStudioIndexRoute
  '/brands/$id/brand-book': typeof AppBrandsIdBrandBookRoute
  '/brands/$id/fonts': typeof AppBrandsIdFontsRoute
  '/brands/$id/palette': typeof AppBrandsIdPaletteRoute
  '/brands/$id/social-icons': typeof AppBrandsIdSocialIconsRoute
  '/developer/apps/$clientId': typeof AppDeveloperAppsClientIdRoute
  '/my-apps/$id/analytics': typeof AppMyAppsIdAnalyticsRoute
  '/my-apps/$id/edit': typeof AppMyAppsIdEditRoute
  '/my-apps/$id/revenue': typeof AppMyAppsIdRevenueRoute
  '/projects/$id/brand-kit': typeof AppProjectsIdBrandKitRoute
  '/projects/$id/fonts': typeof AppProjectsIdFontsRoute
  '/projects/$id/guidelines': typeof AppProjectsIdGuidelinesRoute
  '/projects/$id/hub': typeof AppProjectsIdHubRoute
  '/projects/$id/logo-files': typeof AppProjectsIdLogoFilesRoute
  '/projects/$id/palettes': typeof AppProjectsIdPalettesRoute
  '/projects/$id/social': typeof AppProjectsIdSocialRoute
  '/projects/$id/websites': typeof AppProjectsIdWebsitesRoute
  '/brands/$id': typeof AppBrandsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-info': typeof AiInfoRoute
  '/brand-kit': typeof BrandKitRoute
  '/claim-invitation': typeof ClaimInvitationRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reserve': typeof ReserveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/editor': typeof AppEditorRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/generate': typeof AppGenerateRoute
  '/_app/icons': typeof AppIconsRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/logos': typeof AppLogosRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/present': typeof AppPresentRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/saved-apps': typeof AppSavedAppsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/wizard': typeof AppWizardRoute
  '/_app/your-apps': typeof AppYourAppsRoute
  '/apps/$id': typeof AppsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brand-templates/$id': typeof BrandTemplatesIdRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/connect/authorize': typeof ConnectAuthorizeRoute
  '/create_/branding': typeof CreateBrandingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/outreach/unsubscribe': typeof OutreachUnsubscribeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/brand-templates/': typeof BrandTemplatesIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_app/admin/$section': typeof AppAdminSectionRoute
  '/_app/apps/add': typeof AppAppsAddRoute
  '/_app/assets/$id': typeof AppAssetsIdRoute
  '/_app/brand/$id': typeof AppBrandIdRoute
  '/_app/brands/$id': typeof AppBrandsIdRouteWithChildren
  '/_app/create/chat': typeof AppCreateChatRoute
  '/_app/create/generate': typeof AppCreateGenerateRoute
  '/_app/designs/$id': typeof AppDesignsIdRoute
  '/_app/developer/activate': typeof AppDeveloperActivateRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/rocket/$id': typeof AppRocketIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/studio/$id': typeof AppStudioIdRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/share/asset/$token': typeof ShareAssetTokenRoute
  '/share/project/$token': typeof ShareProjectTokenRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/brand/': typeof AppBrandIndexRoute
  '/_app/brands/': typeof AppBrandsIndexRoute
  '/_app/create/': typeof AppCreateIndexRoute
  '/_app/designs/': typeof AppDesignsIndexRoute
  '/_app/my-apps/': typeof AppMyAppsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/studio/': typeof AppStudioIndexRoute
  '/_app/brands/$id/brand-book': typeof AppBrandsIdBrandBookRoute
  '/_app/brands/$id/fonts': typeof AppBrandsIdFontsRoute
  '/_app/brands/$id/palette': typeof AppBrandsIdPaletteRoute
  '/_app/brands/$id/social-icons': typeof AppBrandsIdSocialIconsRoute
  '/_app/developer/apps/$clientId': typeof AppDeveloperAppsClientIdRoute
  '/_app/my-apps/$id/analytics': typeof AppMyAppsIdAnalyticsRoute
  '/_app/my-apps/$id/edit': typeof AppMyAppsIdEditRoute
  '/_app/my-apps/$id/revenue': typeof AppMyAppsIdRevenueRoute
  '/_app/projects/$id_/brand-kit': typeof AppProjectsIdBrandKitRoute
  '/_app/projects/$id_/fonts': typeof AppProjectsIdFontsRoute
  '/_app/projects/$id_/guidelines': typeof AppProjectsIdGuidelinesRoute
  '/_app/projects/$id_/hub': typeof AppProjectsIdHubRoute
  '/_app/projects/$id_/logo-files': typeof AppProjectsIdLogoFilesRoute
  '/_app/projects/$id_/palettes': typeof AppProjectsIdPalettesRoute
  '/_app/projects/$id_/social': typeof AppProjectsIdSocialRoute
  '/_app/projects/$id_/websites': typeof AppProjectsIdWebsitesRoute
  '/_app/brands/$id/': typeof AppBrandsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-info'
    | '/brand-kit'
    | '/claim-invitation'
    | '/contact'
    | '/developer'
    | '/discover'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/join'
    | '/launch'
    | '/login'
    | '/media-kit'
    | '/pricing'
    | '/privacy'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/start'
    | '/submit'
    | '/terms'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/editor'
    | '/files'
    | '/generate'
    | '/icons'
    | '/insights'
    | '/library'
    | '/logos'
    | '/notifications'
    | '/present'
    | '/saved'
    | '/saved-apps'
    | '/settings'
    | '/templates'
    | '/trash'
    | '/wizard'
    | '/your-apps'
    | '/apps/$id'
    | '/auth/callback'
    | '/blog/$slug'
    | '/brand-templates/$id'
    | '/compare/$slug'
    | '/connect/authorize'
    | '/create/branding'
    | '/invite/$token'
    | '/outreach/unsubscribe'
    | '/resources/$slug'
    | '/tools/$slug'
    | '/blog/'
    | '/brand-templates/'
    | '/compare/'
    | '/resources/'
    | '/tools/'
    | '/admin/$section'
    | '/apps/add'
    | '/assets/$id'
    | '/brand/$id'
    | '/brands/$id'
    | '/create/chat'
    | '/create/generate'
    | '/designs/$id'
    | '/developer/activate'
    | '/projects/$id'
    | '/projects/new'
    | '/rocket/$id'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/team'
    | '/studio/$id'
    | '/blog/author/$id'
    | '/share/asset/$token'
    | '/share/project/$token'
    | '/assets/'
    | '/brand/'
    | '/brands/'
    | '/create/'
    | '/designs/'
    | '/my-apps/'
    | '/projects/'
    | '/settings/'
    | '/studio/'
    | '/brands/$id/brand-book'
    | '/brands/$id/fonts'
    | '/brands/$id/palette'
    | '/brands/$id/social-icons'
    | '/developer/apps/$clientId'
    | '/my-apps/$id/analytics'
    | '/my-apps/$id/edit'
    | '/my-apps/$id/revenue'
    | '/projects/$id/brand-kit'
    | '/projects/$id/fonts'
    | '/projects/$id/guidelines'
    | '/projects/$id/hub'
    | '/projects/$id/logo-files'
    | '/projects/$id/palettes'
    | '/projects/$id/social'
    | '/projects/$id/websites'
    | '/brands/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-info'
    | '/brand-kit'
    | '/claim-invitation'
    | '/contact'
    | '/developer'
    | '/discover'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/join'
    | '/launch'
    | '/login'
    | '/media-kit'
    | '/pricing'
    | '/privacy'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/start'
    | '/submit'
    | '/terms'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/editor'
    | '/files'
    | '/generate'
    | '/icons'
    | '/insights'
    | '/library'
    | '/logos'
    | '/notifications'
    | '/present'
    | '/saved'
    | '/saved-apps'
    | '/templates'
    | '/trash'
    | '/wizard'
    | '/your-apps'
    | '/apps/$id'
    | '/auth/callback'
    | '/blog/$slug'
    | '/brand-templates/$id'
    | '/compare/$slug'
    | '/connect/authorize'
    | '/create/branding'
    | '/invite/$token'
    | '/outreach/unsubscribe'
    | '/resources/$slug'
    | '/tools/$slug'
    | '/blog'
    | '/brand-templates'
    | '/compare'
    | '/resources'
    | '/tools'
    | '/admin/$section'
    | '/apps/add'
    | '/assets/$id'
    | '/brand/$id'
    | '/create/chat'
    | '/create/generate'
    | '/designs/$id'
    | '/developer/activate'
    | '/projects/$id'
    | '/projects/new'
    | '/rocket/$id'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/team'
    | '/studio/$id'
    | '/blog/author/$id'
    | '/share/asset/$token'
    | '/share/project/$token'
    | '/assets'
    | '/brand'
    | '/brands'
    | '/create'
    | '/designs'
    | '/my-apps'
    | '/projects'
    | '/settings'
    | '/studio'
    | '/brands/$id/brand-book'
    | '/brands/$id/fonts'
    | '/brands/$id/palette'
    | '/brands/$id/social-icons'
    | '/developer/apps/$clientId'
    | '/my-apps/$id/analytics'
    | '/my-apps/$id/edit'
    | '/my-apps/$id/revenue'
    | '/projects/$id/brand-kit'
    | '/projects/$id/fonts'
    | '/projects/$id/guidelines'
    | '/projects/$id/hub'
    | '/projects/$id/logo-files'
    | '/projects/$id/palettes'
    | '/projects/$id/social'
    | '/projects/$id/websites'
    | '/brands/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/ai-info'
    | '/brand-kit'
    | '/claim-invitation'
    | '/contact'
    | '/developer'
    | '/discover'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/join'
    | '/launch'
    | '/login'
    | '/media-kit'
    | '/pricing'
    | '/privacy'
    | '/reserve'
    | '/reset-password'
    | '/signup'
    | '/start'
    | '/submit'
    | '/terms'
    | '/verify-email'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/editor'
    | '/_app/files'
    | '/_app/generate'
    | '/_app/icons'
    | '/_app/insights'
    | '/_app/library'
    | '/_app/logos'
    | '/_app/notifications'
    | '/_app/present'
    | '/_app/saved'
    | '/_app/saved-apps'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/trash'
    | '/_app/wizard'
    | '/_app/your-apps'
    | '/apps/$id'
    | '/auth/callback'
    | '/blog/$slug'
    | '/brand-templates/$id'
    | '/compare/$slug'
    | '/connect/authorize'
    | '/create_/branding'
    | '/invite/$token'
    | '/outreach/unsubscribe'
    | '/resources/$slug'
    | '/tools/$slug'
    | '/blog/'
    | '/brand-templates/'
    | '/compare/'
    | '/resources/'
    | '/tools/'
    | '/_app/admin/$section'
    | '/_app/apps/add'
    | '/_app/assets/$id'
    | '/_app/brand/$id'
    | '/_app/brands/$id'
    | '/_app/create/chat'
    | '/_app/create/generate'
    | '/_app/designs/$id'
    | '/_app/developer/activate'
    | '/_app/projects/$id'
    | '/_app/projects/new'
    | '/_app/rocket/$id'
    | '/_app/settings/account'
    | '/_app/settings/billing'
    | '/_app/settings/integrations'
    | '/_app/settings/notifications'
    | '/_app/settings/profile'
    | '/_app/settings/team'
    | '/_app/studio/$id'
    | '/blog/author/$id'
    | '/share/asset/$token'
    | '/share/project/$token'
    | '/_app/assets/'
    | '/_app/brand/'
    | '/_app/brands/'
    | '/_app/create/'
    | '/_app/designs/'
    | '/_app/my-apps/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/studio/'
    | '/_app/brands/$id/brand-book'
    | '/_app/brands/$id/fonts'
    | '/_app/brands/$id/palette'
    | '/_app/brands/$id/social-icons'
    | '/_app/developer/apps/$clientId'
    | '/_app/my-apps/$id/analytics'
    | '/_app/my-apps/$id/edit'
    | '/_app/my-apps/$id/revenue'
    | '/_app/projects/$id_/brand-kit'
    | '/_app/projects/$id_/fonts'
    | '/_app/projects/$id_/guidelines'
    | '/_app/projects/$id_/hub'
    | '/_app/projects/$id_/logo-files'
    | '/_app/projects/$id_/palettes'
    | '/_app/projects/$id_/social'
    | '/_app/projects/$id_/websites'
    | '/_app/brands/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiInfoRoute: typeof AiInfoRoute
  BrandKitRoute: typeof BrandKitRoute
  ClaimInvitationRoute: typeof ClaimInvitationRoute
  ContactRoute: typeof ContactRoute
  DeveloperRoute: typeof DeveloperRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  MediaKitRoute: typeof MediaKitRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReserveRoute: typeof ReserveRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AppsIdRoute: typeof AppsIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BrandTemplatesIdRoute: typeof BrandTemplatesIdRoute
  CompareSlugRoute: typeof CompareSlugRoute
  ConnectAuthorizeRoute: typeof ConnectAuthorizeRoute
  CreateBrandingRoute: typeof CreateBrandingRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OutreachUnsubscribeRoute: typeof OutreachUnsubscribeRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BrandTemplatesIndexRoute: typeof BrandTemplatesIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  BlogAuthorIdRoute: typeof BlogAuthorIdRoute
  ShareAssetTokenRoute: typeof ShareAssetTokenRoute
  ShareProjectTokenRoute: typeof ShareProjectTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-info': {
      id: '/ai-info'
      path: '/ai-info'
      fullPath: '/ai-info'
      preLoaderRoute: typeof AiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-invitation': {
      id: '/claim-invitation'
      path: '/claim-invitation'
      fullPath: '/claim-invitation'
      preLoaderRoute: typeof ClaimInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editor': {
      id: '/_app/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generate': {
      id: '/_app/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/icons': {
      id: '/_app/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof AppIconsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logos': {
      id: '/_app/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof AppLogosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/present': {
      id: '/_app/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof AppPresentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved-apps': {
      id: '/_app/saved-apps'
      path: '/saved-apps'
      fullPath: '/saved-apps'
      preLoaderRoute: typeof AppSavedAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard': {
      id: '/_app/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AppWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/your-apps': {
      id: '/_app/your-apps'
      path: '/your-apps'
      fullPath: '/your-apps'
      preLoaderRoute: typeof AppYourAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/apps/$id': {
      id: '/apps/$id'
      path: '/apps/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AppsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-templates/': {
      id: '/brand-templates/'
      path: '/brand-templates'
      fullPath: '/brand-templates/'
      preLoaderRoute: typeof BrandTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-templates/$id': {
      id: '/brand-templates/$id'
      path: '/brand-templates/$id'
      fullPath: '/brand-templates/$id'
      preLoaderRoute: typeof BrandTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/authorize': {
      id: '/connect/authorize'
      path: '/connect/authorize'
      fullPath: '/connect/authorize'
      preLoaderRoute: typeof ConnectAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create_/branding': {
      id: '/create_/branding'
      path: '/create/branding'
      fullPath: '/create/branding'
      preLoaderRoute: typeof CreateBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/unsubscribe': {
      id: '/outreach/unsubscribe'
      path: '/outreach/unsubscribe'
      fullPath: '/outreach/unsubscribe'
      preLoaderRoute: typeof OutreachUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/$section': {
      id: '/_app/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AppAdminSectionRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/apps/add': {
      id: '/_app/apps/add'
      path: '/apps/add'
      fullPath: '/apps/add'
      preLoaderRoute: typeof AppAppsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$id': {
      id: '/_app/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AppAssetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand/': {
      id: '/_app/brand/'
      path: '/brand'
      fullPath: '/brand/'
      preLoaderRoute: typeof AppBrandIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand/$id': {
      id: '/_app/brand/$id'
      path: '/brand/$id'
      fullPath: '/brand/$id'
      preLoaderRoute: typeof AppBrandIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/': {
      id: '/_app/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AppBrandsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$id': {
      id: '/_app/brands/$id'
      path: '/brands/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof AppBrandsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create/': {
      id: '/_app/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof AppCreateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create/chat': {
      id: '/_app/create/chat'
      path: '/create/chat'
      fullPath: '/create/chat'
      preLoaderRoute: typeof AppCreateChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create/generate': {
      id: '/_app/create/generate'
      path: '/create/generate'
      fullPath: '/create/generate'
      preLoaderRoute: typeof AppCreateGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designs/': {
      id: '/_app/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof AppDesignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designs/$id': {
      id: '/_app/designs/$id'
      path: '/designs/$id'
      fullPath: '/designs/$id'
      preLoaderRoute: typeof AppDesignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer/activate': {
      id: '/_app/developer/activate'
      path: '/developer/activate'
      fullPath: '/developer/activate'
      preLoaderRoute: typeof AppDeveloperActivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-apps/': {
      id: '/_app/my-apps/'
      path: '/my-apps'
      fullPath: '/my-apps/'
      preLoaderRoute: typeof AppMyAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rocket/$id': {
      id: '/_app/rocket/$id'
      path: '/rocket/$id'
      fullPath: '/rocket/$id'
      preLoaderRoute: typeof AppRocketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/studio/': {
      id: '/_app/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AppStudioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio/$id': {
      id: '/_app/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof AppStudioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/author/$id': {
      id: '/blog/author/$id'
      path: '/blog/author/$id'
      fullPath: '/blog/author/$id'
      preLoaderRoute: typeof BlogAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/asset/$token': {
      id: '/share/asset/$token'
      path: '/share/asset/$token'
      fullPath: '/share/asset/$token'
      preLoaderRoute: typeof ShareAssetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/project/$token': {
      id: '/share/project/$token'
      path: '/share/project/$token'
      fullPath: '/share/project/$token'
      preLoaderRoute: typeof ShareProjectTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/brands/$id/': {
      id: '/_app/brands/$id/'
      path: '/'
      fullPath: '/brands/$id/'
      preLoaderRoute: typeof AppBrandsIdIndexRouteImport
      parentRoute: typeof AppBrandsIdRoute
    }
    '/_app/brands/$id/brand-book': {
      id: '/_app/brands/$id/brand-book'
      path: '/brand-book'
      fullPath: '/brands/$id/brand-book'
      preLoaderRoute: typeof AppBrandsIdBrandBookRouteImport
      parentRoute: typeof AppBrandsIdRoute
    }
    '/_app/brands/$id/fonts': {
      id: '/_app/brands/$id/fonts'
      path: '/fonts'
      fullPath: '/brands/$id/fonts'
      preLoaderRoute: typeof AppBrandsIdFontsRouteImport
      parentRoute: typeof AppBrandsIdRoute
    }
    '/_app/brands/$id/palette': {
      id: '/_app/brands/$id/palette'
      path: '/palette'
      fullPath: '/brands/$id/palette'
      preLoaderRoute: typeof AppBrandsIdPaletteRouteImport
      parentRoute: typeof AppBrandsIdRoute
    }
    '/_app/brands/$id/social-icons': {
      id: '/_app/brands/$id/social-icons'
      path: '/social-icons'
      fullPath: '/brands/$id/social-icons'
      preLoaderRoute: typeof AppBrandsIdSocialIconsRouteImport
      parentRoute: typeof AppBrandsIdRoute
    }
    '/_app/developer/apps/$clientId': {
      id: '/_app/developer/apps/$clientId'
      path: '/developer/apps/$clientId'
      fullPath: '/developer/apps/$clientId'
      preLoaderRoute: typeof AppDeveloperAppsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-apps/$id/analytics': {
      id: '/_app/my-apps/$id/analytics'
      path: '/my-apps/$id/analytics'
      fullPath: '/my-apps/$id/analytics'
      preLoaderRoute: typeof AppMyAppsIdAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-apps/$id/edit': {
      id: '/_app/my-apps/$id/edit'
      path: '/my-apps/$id/edit'
      fullPath: '/my-apps/$id/edit'
      preLoaderRoute: typeof AppMyAppsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-apps/$id/revenue': {
      id: '/_app/my-apps/$id/revenue'
      path: '/my-apps/$id/revenue'
      fullPath: '/my-apps/$id/revenue'
      preLoaderRoute: typeof AppMyAppsIdRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/brand-kit': {
      id: '/_app/projects/$id_/brand-kit'
      path: '/projects/$id/brand-kit'
      fullPath: '/projects/$id/brand-kit'
      preLoaderRoute: typeof AppProjectsIdBrandKitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/fonts': {
      id: '/_app/projects/$id_/fonts'
      path: '/projects/$id/fonts'
      fullPath: '/projects/$id/fonts'
      preLoaderRoute: typeof AppProjectsIdFontsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/guidelines': {
      id: '/_app/projects/$id_/guidelines'
      path: '/projects/$id/guidelines'
      fullPath: '/projects/$id/guidelines'
      preLoaderRoute: typeof AppProjectsIdGuidelinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/hub': {
      id: '/_app/projects/$id_/hub'
      path: '/projects/$id/hub'
      fullPath: '/projects/$id/hub'
      preLoaderRoute: typeof AppProjectsIdHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/logo-files': {
      id: '/_app/projects/$id_/logo-files'
      path: '/projects/$id/logo-files'
      fullPath: '/projects/$id/logo-files'
      preLoaderRoute: typeof AppProjectsIdLogoFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/palettes': {
      id: '/_app/projects/$id_/palettes'
      path: '/projects/$id/palettes'
      fullPath: '/projects/$id/palettes'
      preLoaderRoute: typeof AppProjectsIdPalettesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/social': {
      id: '/_app/projects/$id_/social'
      path: '/projects/$id/social'
      fullPath: '/projects/$id/social'
      preLoaderRoute: typeof AppProjectsIdSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/websites': {
      id: '/_app/projects/$id_/websites'
      path: '/projects/$id/websites'
      fullPath: '/projects/$id/websites'
      preLoaderRoute: typeof AppProjectsIdWebsitesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminSectionRoute: typeof AppAdminSectionRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminSectionRoute: AppAdminSectionRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppBrandsIdRouteChildren {
  AppBrandsIdBrandBookRoute: typeof AppBrandsIdBrandBookRoute
  AppBrandsIdFontsRoute: typeof AppBrandsIdFontsRoute
  AppBrandsIdPaletteRoute: typeof AppBrandsIdPaletteRoute
  AppBrandsIdSocialIconsRoute: typeof AppBrandsIdSocialIconsRoute
  AppBrandsIdIndexRoute: typeof AppBrandsIdIndexRoute
}

const AppBrandsIdRouteChildren: AppBrandsIdRouteChildren = {
  AppBrandsIdBrandBookRoute: AppBrandsIdBrandBookRoute,
  AppBrandsIdFontsRoute: AppBrandsIdFontsRoute,
  AppBrandsIdPaletteRoute: AppBrandsIdPaletteRoute,
  AppBrandsIdSocialIconsRoute: AppBrandsIdSocialIconsRoute,
  AppBrandsIdIndexRoute: AppBrandsIdIndexRoute,
}

const AppBrandsIdRouteWithChildren = AppBrandsIdRoute._addFileChildren(
  AppBrandsIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEditorRoute: typeof AppEditorRoute
  AppFilesRoute: typeof AppFilesRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppIconsRoute: typeof AppIconsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppLogosRoute: typeof AppLogosRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPresentRoute: typeof AppPresentRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSavedAppsRoute: typeof AppSavedAppsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTrashRoute: typeof AppTrashRoute
  AppWizardRoute: typeof AppWizardRoute
  AppYourAppsRoute: typeof AppYourAppsRoute
  AppAppsAddRoute: typeof AppAppsAddRoute
  AppAssetsIdRoute: typeof AppAssetsIdRoute
  AppBrandIdRoute: typeof AppBrandIdRoute
  AppBrandsIdRoute: typeof AppBrandsIdRouteWithChildren
  AppCreateChatRoute: typeof AppCreateChatRoute
  AppCreateGenerateRoute: typeof AppCreateGenerateRoute
  AppDesignsIdRoute: typeof AppDesignsIdRoute
  AppDeveloperActivateRoute: typeof AppDeveloperActivateRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppRocketIdRoute: typeof AppRocketIdRoute
  AppStudioIdRoute: typeof AppStudioIdRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppBrandIndexRoute: typeof AppBrandIndexRoute
  AppBrandsIndexRoute: typeof AppBrandsIndexRoute
  AppCreateIndexRoute: typeof AppCreateIndexRoute
  AppDesignsIndexRoute: typeof AppDesignsIndexRoute
  AppMyAppsIndexRoute: typeof AppMyAppsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppStudioIndexRoute: typeof AppStudioIndexRoute
  AppDeveloperAppsClientIdRoute: typeof AppDeveloperAppsClientIdRoute
  AppMyAppsIdAnalyticsRoute: typeof AppMyAppsIdAnalyticsRoute
  AppMyAppsIdEditRoute: typeof AppMyAppsIdEditRoute
  AppMyAppsIdRevenueRoute: typeof AppMyAppsIdRevenueRoute
  AppProjectsIdBrandKitRoute: typeof AppProjectsIdBrandKitRoute
  AppProjectsIdFontsRoute: typeof AppProjectsIdFontsRoute
  AppProjectsIdGuidelinesRoute: typeof AppProjectsIdGuidelinesRoute
  AppProjectsIdHubRoute: typeof AppProjectsIdHubRoute
  AppProjectsIdLogoFilesRoute: typeof AppProjectsIdLogoFilesRoute
  AppProjectsIdPalettesRoute: typeof AppProjectsIdPalettesRoute
  AppProjectsIdSocialRoute: typeof AppProjectsIdSocialRoute
  AppProjectsIdWebsitesRoute: typeof AppProjectsIdWebsitesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEditorRoute: AppEditorRoute,
  AppFilesRoute: AppFilesRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppIconsRoute: AppIconsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppLogosRoute: AppLogosRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPresentRoute: AppPresentRoute,
  AppSavedRoute: AppSavedRoute,
  AppSavedAppsRoute: AppSavedAppsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTrashRoute: AppTrashRoute,
  AppWizardRoute: AppWizardRoute,
  AppYourAppsRoute: AppYourAppsRoute,
  AppAppsAddRoute: AppAppsAddRoute,
  AppAssetsIdRoute: AppAssetsIdRoute,
  AppBrandIdRoute: AppBrandIdRoute,
  AppBrandsIdRoute: AppBrandsIdRouteWithChildren,
  AppCreateChatRoute: AppCreateChatRoute,
  AppCreateGenerateRoute: AppCreateGenerateRoute,
  AppDesignsIdRoute: AppDesignsIdRoute,
  AppDeveloperActivateRoute: AppDeveloperActivateRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppRocketIdRoute: AppRocketIdRoute,
  AppStudioIdRoute: AppStudioIdRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppBrandIndexRoute: AppBrandIndexRoute,
  AppBrandsIndexRoute: AppBrandsIndexRoute,
  AppCreateIndexRoute: AppCreateIndexRoute,
  AppDesignsIndexRoute: AppDesignsIndexRoute,
  AppMyAppsIndexRoute: AppMyAppsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppStudioIndexRoute: AppStudioIndexRoute,
  AppDeveloperAppsClientIdRoute: AppDeveloperAppsClientIdRoute,
  AppMyAppsIdAnalyticsRoute: AppMyAppsIdAnalyticsRoute,
  AppMyAppsIdEditRoute: AppMyAppsIdEditRoute,
  AppMyAppsIdRevenueRoute: AppMyAppsIdRevenueRoute,
  AppProjectsIdBrandKitRoute: AppProjectsIdBrandKitRoute,
  AppProjectsIdFontsRoute: AppProjectsIdFontsRoute,
  AppProjectsIdGuidelinesRoute: AppProjectsIdGuidelinesRoute,
  AppProjectsIdHubRoute: AppProjectsIdHubRoute,
  AppProjectsIdLogoFilesRoute: AppProjectsIdLogoFilesRoute,
  AppProjectsIdPalettesRoute: AppProjectsIdPalettesRoute,
  AppProjectsIdSocialRoute: AppProjectsIdSocialRoute,
  AppProjectsIdWebsitesRoute: AppProjectsIdWebsitesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AiInfoRoute: AiInfoRoute,
  BrandKitRoute: BrandKitRoute,
  ClaimInvitationRoute: ClaimInvitationRoute,
  ContactRoute: ContactRoute,
  DeveloperRoute: DeveloperRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  MediaKitRoute: MediaKitRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReserveRoute: ReserveRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AppsIdRoute: AppsIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  BrandTemplatesIdRoute: BrandTemplatesIdRoute,
  CompareSlugRoute: CompareSlugRoute,
  ConnectAuthorizeRoute: ConnectAuthorizeRoute,
  CreateBrandingRoute: CreateBrandingRoute,
  InviteTokenRoute: InviteTokenRoute,
  OutreachUnsubscribeRoute: OutreachUnsubscribeRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BrandTemplatesIndexRoute: BrandTemplatesIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  BlogAuthorIdRoute: BlogAuthorIdRoute,
  ShareAssetTokenRoute: ShareAssetTokenRoute,
  ShareProjectTokenRoute: ShareProjectTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
